### ISSUE TITLE
Stars that have been posted to a group appear on a users wall/profile

### ISSUE THREAD

**Issue by cartisan** [cafca/souma#112]
Reproduce: 
1. Create a star in a group
2. Click on homepage or universe

There is a check that looks up weather a stars group_id is set, and if it is, doesn't display the star in universe context. Probably this property is gone with migration to starmaps, so the check no always passes.

**Comment by cafca** [comment]
The universe view is like an index right now, it contains all posts with publishing state >= 0 (not deleted or unavailable). We could even rename it to 'index'. Why would you exclude group posts from that?

**Comment by cartisan** [comment]
I didn't know what the universe page was exactly for, thought of it as a combination of all persona pages. Do we want to see stars we made in a group outside of the group context? Dunno, to be honest!

**Comment by cafca** [comment]
I wouldn't mix it up too much as well. At least not without explicit communication of the origin of the content. 

Universe is an exemption from that though, because I think it makes sense to have a place where _all_ Stars which are visible to me can be browsed, sortable by different attributes. It should have a different layout though. Right now it looks like it was supposed to be used for browsing, while it should look more like an actual index.
