### ISSUE TITLE
Writing to hosts file is problematic and should at least be optional

### ISSUE THREAD

**Issue by lmeuser** [cafca/souma#178]
The fact that it wants to write to /etc/hosts makes it impossible to install souma without admin rights, in a contained environment (like a python virtualenv), or if you don't want random apps changing critical system configuration files, and I don't think there's an uninstall mechanism that removes it again. For all these reasons, I think using the app.souma domain and changing the hosts file is a very questionable design decision.

I think changing the hosts file should at the very least be optional. Otherwise, souma simply does not work if you don't have admin rights. Also, if the change does not happen during the installation, souma should offer an option to do that later instead of pestering the user for the admin password every time it is started (that is the current behavior on OS X, no idea for other systems).

I don't have a definite answer on how to replace the app.souma domain, but I would suggest either simply using the localhost name, or changing the DNS entry of app.souma.io (or something like that) to 127.0.0.1 and just using that as the app URL.

**Comment by cafca** [comment]
Thank you Lukas for taking the time to write all that down. Using `app.souma` is a temporary solution and we haven't found a fix for the problems you are mentioning. 

The behavior I would like to see is that you can go to `http://souma.io` and get redirected into the app if you have it installed. This could be done by adding an /etc/hosts entry for `app.souma.io` like you suggested. There could be a script on `http://souma.io` that checks whether `http://localhost:xxxx/` responds to HTTP requests and redirects the browser if so.

The second thing is that links inside the app should be shareable. That is, if I send you a link to a Souma page and you don't have the client, you should still be able to open the link. You would end up on a page where you can download the Souma client instead. It's possible to do that by using `app.souma.io`, but not if we give the option of using `localhost` instead.

The problem is of course that all this still requires admin rights and access to `/etc/hosts`. One alternative would be to have `app.souma.io` include a script that asynchronously loads the page content from localhost. Then we don't need to modify /etc/hosts but this has the downside that we get a history of all Souma pages visited by users in our server logs for `souma.io`, which we don't want (privacy).

I don't know the perfect solution. For now, we will go with using `app.souma.io` and still require admin permissions by default. Later (maybe for the beta) we can implement a fallback behavior if requesting admin permission fails. Then we ask the user if she just doesn't have those permissions and change the config so that localhost is used.

**Comment by cafca** [comment]
Also #179 (Warn the user before requiring admin permissions for modifying /etc/hosts )

**Comment by lmeuser** [comment]
My suggestion was (or at least was meant to be) to add a DNS entry pointing app.souma.io to 127.0.0.1 to the DNS server for the domain, not to /etc/hosts. This would not require admin permissions on the user's computer, and everyone going to app.souma.io would automatically access their own souma server.

**Comment by cafca** [comment]
That's possible? I thought you accidentally wrote dns entry. Really interesting idea! I will look into it next week. 

—
